Disable popup windows on desktop
KevinnZou/compose-webview-multiplatform pull request #45
Opened 2023-11-16 18:55 UTC by DatL4g

Popup windows can  be enabled/disabled on desktop now, default is unchanged (enabled)

2023-11-18 02:32 UTC, KevinnZou requested changes
Thank you for your contributions! Everything looks great. The only thing that needs to be changed is reformatting the code. I added a code check CI last week, which runs the ktlint check for each PR.

To fix the code, run the `ktlintFormat` task locally and submit it again. For easier management in the future, use the `setUpGitHooks` task to set up git hooks. This will automatically reformat the code whenever you commit.

2023-11-18 16:40 UTC, DatL4g commented
@KevinnZou 
Please create a github action which has write permission on pull requests and runs the task instead.
I prevent GitHooks on my system for security reasons

2023-11-22 08:57 UTC, KevinnZou commented
> @KevinnZou Please create a github action which has write permission on pull requests and runs the task instead. I prevent GitHooks on my system for security reasons

I prefer not to grant write permission to GitHub Actions for some reason. If you don't want to use GitHooks, please run `ktlintFormat` on your local machine. Thank you for your contribution!

2023-11-24 01:37 UTC, KevinnZou approved these changes

2023-11-24 01:37 UTC, merged